"""add print logs table

Revision ID: c491056dde88
Revises: 80f2b0b88f51
Create Date: 2026-02-01 22:11:16.316306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c491056dde88'
down_revision: Union[str, Sequence[str], None] = '80f2b0b88f51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'print_logs',
        sa.Column('printer_id', sa.INTEGER(), nullable=False),
        sa.Column('pedido_id', sa.INTEGER(), nullable=False),
        sa.Column('item_id', sa.INTEGER(), nullable=True),
        sa.Column('status', sa.VARCHAR(length=7), nullable=False),
        sa.Column('error_message', sa.VARCHAR(), nullable=True),
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column(
            'created_at',
            sa.DATETIME(),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id']),
        sa.ForeignKeyConstraint(['printer_id'], ['machines.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table('print_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_print_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_print_logs_pedido_id'), ['pedido_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_print_logs_printer_id'), ['printer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('print_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_print_logs_id'))
        batch_op.drop_index(batch_op.f('ix_print_logs_pedido_id'))
        batch_op.drop_index(batch_op.f('ix_print_logs_printer_id'))

    op.drop_table('print_logs')

    # ### end Alembic commands ###
